spring:
  application:
    name: ai-agent
  ai:
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8127
    #        stdio:
    #          servers-configuration: classpath:mcp-server.json
    dashscope:
      api-key: 
      chat:
        options:
          model: qwen-plus
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        max-document-batch-size: 10000
  datasource:
    url: jdbc:mysql://localhost:3306/sqltest?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:postgresql://:5432/agent
#    username: 
#    password: 
#    driver-class-name: org.postgresql.Driver
#    dynamic:
#      primary: pgsql
#      datasource:
#        pgsql:
#
#        mysql:
#
#      strict: false
server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ai.agent.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    root: INFO

tool:
  search:
    api_key: 
